CREATE TABLE IF NOT EXISTS `temporary_leave_requests` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` bigint(20) unsigned NOT NULL,
  `supervisor_id` bigint(20) unsigned NULL,
  `leave_type` enum('weekend','holiday','emergency','medical','family_visit','other') NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `return_date` date NOT NULL,
  `destination` varchar(255) NOT NULL,
  `emergency_contact_name` varchar(255) NOT NULL,
  `emergency_contact_phone` varchar(255) NOT NULL,
  `reason` text NOT NULL,
  `supervisor_approval` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status` enum('draft','submitted','approved','rejected','completed','overdue') NOT NULL DEFAULT 'draft',
  `supervisor_notes` text NULL,
  `approved_at` timestamp NULL,
  `returned_at` timestamp NULL,
  `room_secured` tinyint(1) NOT NULL DEFAULT 0,
  `security_checklist` json NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `temporary_leave_requests_student_id_status_index` (`student_id`,`status`),
  KEY `temporary_leave_requests_supervisor_id_supervisor_approval_index` (`supervisor_id`,`supervisor_approval`),
  KEY `temporary_leave_requests_start_date_end_date_index` (`start_date`,`end_date`),
  CONSTRAINT `temporary_leave_requests_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `temporary_leave_requests_supervisor_id_foreign` FOREIGN KEY (`supervisor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;